### ISSUE TITLE
Is there a way to get the plain text from the editor?

### ISSUE THREAD

**Issue by mayur9293** [stevermeister/ngx-wig#75]
Is there a way to just get plain text from the editor removing all the HTML tags??

**Comment by AdamMadrzejewski** [comment]
Since you have access to the variable containing HTML string, you can do all operations that can be made on strings, including striping html tags from it. It's just JavaScript operation on string and there are a lot of solutions on internet. Have a look here:

[https://stackoverflow.com/questions/822452/strip-html-from-text-javascript](https://stackoverflow.com/questions/822452/strip-html-from-text-javascript)

**Comment by mayur9293** [comment]
Oh wow... It worked. Thanks for the help.
